version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: crates
      POSTGRES_PASSWORD: crates
      POSTGRES_DB: crates
    volumes: [dbdata:/var/lib/postgresql/data]
    ports: ["5432:5432"]

  redis:
    image: redis:7
    ports: ["6379:6379"]
volumes:
  dbdata:
